name: Deploy Flask App

on:
  push:
    branches:
      - main  # Thực hiện deploy khi có code push lên nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Phiên bản Python phù hợp với Flask

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd /path/to/your/app &&
          git pull &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          sudo systemctl restart your-flask-app.service"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
